### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by sk9g3** [Studyxnet/LearningMVVM#1]
na minha viewModel, como faria para ter navegação. Eu criei um service:

``` c#
public async System.Threading.Tasks.Task NavigationTo (Page page)
        {
            await Projeto.App.Current.MainPage.Navigation.PushAsync (page);
        }
```

mas na minha viewModel não consigo chamar minha view (Register.xaml)

``` c#
public void GoToRegister(){
            _navigationService.NavigationTo(new Register());
        }
```

**Comment by rafaelrmou** [comment]
@sk9g3
O correto na verdade é, na instância da sua ViewModel você receber a Navigation da Página atual (this.Navigation) e dentro do seu Command  você chamar esse referência e mandar a página nova :)

Algo como:

public class minhaVM{

public Navigation _nav{
get;
set;
}

public ICommand NavegarParaHome{
get{
_nav.PushAsync(new Home());
}
}
}

e sua Page:

public class Pagina : ContentPage{

public Pagina(){
BindingContext = new MinhaVM(){_nav = this.Navigation};
}

}

Veja mais sobre Xamarin no nosso blog: www.studyxnet.com.br

**Comment by sk9g3** [comment]
muito obrigado @rafaelrmou , e sou seguidor do seu blog, e pretendo fazer a certificação do Xamarin :)

**Comment by rafaelrmou** [comment]
@sk9g3 lembre-se de que, para se certificar, é necessário ingressas na xamarin university:

http://studyxnet.com.br/xamarin-university-sobre-a-certificacao/

https://university.xamarin.com/resources/certification
